[workspace]
resolver = "2"
members = [
    "engine",
    "bench",
]
exclude = [
    "engine/fuzz",
]

[workspace.dependencies]
tempfile = "3"

[workspace.metadata]
# to run with: cargo test -q --features engine/http-test