[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap  = { version = "4", features = ["derive"] }
anyhow = "1.0.98"
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }

[lib]
name = "engine"
path = "src/lib.rs"

