[package]
name = "kyrodb-engine"
version = "0.1.0"
edition = "2021"
authors = ["KyroDB Team <kishan@kyrodb.com>"]
license = "BSL"
description = "High-performance vector database for RAG workloads"
repository = "https://github.com/vatskishan03/KyroDB"
readme = "../README.md"
keywords = ["vector-database", "hnsw", "learned-cache", "rag", "embeddings"]
categories = ["database-implementations", "machine-learning"]

[lib]
name = "kyrodb_engine"
path = "src/lib.rs"

[features]
default = []
# Phase 0 Week 3-8: Enable learned cache with RMI
learned-cache = []
# Benchmarking: disable metrics for zero-overhead measurements
bench-no-metrics = []

[dependencies]
# Phase 0 Week 1-2: HNSW vector search
hnsw_rs = "0.3"
anyhow = "1.0"

# Phase 0 Week 3-8: RMI for learned cache (no external deps, pure Rust)

# Phase 0 Week 9-12: A/B testing framework + minimal persistence
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync", "macros", "fs", "io-util"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
parking_lot = "0.12"  # Fast RwLock for cache

# Phase 0 Week 13-16: Full persistence (will add when needed)
# bincode = "1.3"
# memmap2 = "0.9"

[dev-dependencies]
# Phase 0 Week 1-2: Testing HNSW recall guarantees
proptest = "1.0"
rand = "0.8"
tempfile = "3.8"  # For testing file persistence

[[bench]]
name = "hnsw_knn"
harness = false

[[bench]]
name = "learned_cache"
harness = false

[[bench]]
name = "access_logger"
harness = false

[dependencies.criterion]
version = "0.5"
optional = true

[dev-dependencies.criterion]
version = "0.5"
features = ["html_reports"]

[build-dependencies]
# None needed yet

[package.metadata.docs.rs]
features = ["learned-index"]
