[package]
name = "kyrodb-engine"
version = "0.1.0"
edition = "2021"
authors = ["KyroDB Team <kishanvats2003@gmail.com>"]
license = "Apache-2.0"
description = "High-performance database engine with learned indexes (RMI) and vector search"
repository = "https://github.com/vatskishan03/KyroDB"
homepage = "https://github.com/vatskishan03/KyroDB"
documentation = "https://github.com/vatskishan03/KyroDB"
readme = "../README.md"
keywords = ["database", "kv", "learned-index", "rmi", "vector-search", "durability", "wal"]
categories = ["database-implementations", "data-structures", "concurrency"]
build = "build.rs"

[lib]
name = "kyrodb_engine"
path = "src/lib.rs"

[[bin]]
name = "kyrodb-engine"
path = "src/main.rs"

[features]
# Enable learned-index by default for consistent release binaries
default = ["learned-index", "grpc", "vector-storage"]
learned-index = []
ann-hnsw = ["dep:hora"]
http-test = []
bench-no-metrics = []
# Optional CPU/SIMD build toggles
simd-avx2 = ["dep:wide"]
simd-avx512 = ["dep:wide"]
cpu-native = []
# Failure injection for tests
failpoints = ["dep:fail"]
grpc = ["dep:tonic", "dep:prost", "dep:prost-types"]
tls = ["dep:rustls", "dep:rustls-pemfile", "dep:tokio-rustls"]
rate-limiting = []  # Added feature for optional rate limiting

# Vector Storage and Search Features
vector-storage = ["vector-search", "multimodal-search", "streaming"]
vector-search = ["hnsw-index", "simd-optimization"]
multimodal-search = ["fulltext-search", "metadata-indexing"]
streaming = ["realtime-updates", "websocket-support"]
hnsw-index = ["dep:rand", "dep:rayon", "dep:approx"]
simd-optimization = ["dep:wide", "dep:simdeez"]
fulltext-search = ["dep:tantivy"]
metadata-indexing = []
realtime-updates = []
websocket-support = ["dep:tokio-tungstenite", "dep:futures-util"]

[dependencies]
tokio = { version = "1", features = ["full"] }
clap  = { version = "4", features = ["derive"] }
uuid  = { version = "1", features = ["serde", "v4"] }
chrono= { version = "0.4", features = ["serde"] }
warp = { version = "0.3", features = ["compression"] }
# Removed complex HTTP/2 server dependencies - focusing on client-side optimizations
serde_json = "1.0"
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
sqlparser = "0.40"
hex = "0.4"
prometheus = "0.13"
once_cell = "1"
crc32c = "0.6"
memmap2 = "0.9"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
libc = "0.2"
dashmap = "5"
bytes = "1.5"
rmp-serde = "1.1"  # Added for MessagePack serialization
# ANN library (optional)
hora = { version = "0.1", optional = true }
# Small LRU cache for hot payloads (steady p99)
lru = "0.12"
# Lock-free atomic pointers for read path optimization
arc-swap = "1.6"
# Structured logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "json"] }
# Failpoints for fault injection (optional)
fail = { version = "0.5", optional = true, features = ["failpoints"] }
# gRPC stack (feature-gated)
tonic = { version = "0.11", optional = true, default-features = true, features = ["transport"] }
prost = { version = "0.12", optional = true }
prost-types = { version = "0.12", optional = true }
# TLS support
rustls = { version = "0.21", optional = true }
rustls-pemfile = { version = "1.0", optional = true }
tokio-rustls = { version = "0.24", optional = true }
parking_lot = "0.12.4"

# Vector Storage and Search Dependencies
rand = { version = "0.8", optional = true }
rayon = { version = "1.7", optional = true }
approx = { version = "0.5", optional = true }
wide = { version = "0.7", optional = true }
simdeez = { version = "1.0", optional = true }
tantivy = { version = "0.22", optional = true }
tokio-tungstenite = { version = "0.20", optional = true }
futures-util = { version = "0.3", optional = true }
flatbuffers = "23.1"
fnv = "1.0"  # Fast non-cryptographic hashing
smallvec = { version = "1.11", features = ["serde"] }  # Stack-allocated vectors with serde support
ahash = "0.8"  # Fast hasher for HashMap

[dev-dependencies]
tempfile = "3"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
loom = "0.7"
fail = { version = "0.5", features = ["failpoints"] }
proptest = "1.0"

[build-dependencies]
tonic-build = "0.11"
protoc-bin-vendored = "3"
chrono = { version = "0.4", features = ["serde"] }

[package.metadata.docs.rs]
features = ["learned-index", "ann-hnsw"]
