[package]
name = "engine"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "kyrodb_engine"
path = "src/lib.rs"

[features]
learned-index = []
ann-hnsw = ["dep:hora"]
http-test = []

[dependencies]
tokio = { version = "1", features = ["full"] }
clap  = { version = "4", features = ["derive"] }
uuid  = { version = "1", features = ["serde", "v4"] }
chrono= { version = "0.4", features = ["serde"] }
warp = "0.3"
serde_json = "1.0"
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
sqlparser = "0.40"
hex = "0.4"
prometheus = "0.13"
once_cell = "1"
crc32c = "0.6"
# ANN library (optional)
hora = { version = "0.1", optional = true }

[dev-dependencies]
tempfile = "3"

[package.metadata.docs.rs]
features = ["learned-index", "ann-hnsw"]
