[package]
name = "kyrodb-engine"
version = "0.1.0"
edition = "2021"
authors = ["KyroDB Team <team@kyrodb.dev>"]
license = "Apache-2.0"
description = "High-performance database engine with learned indexes (RMI) and vector search"
repository = "https://github.com/vatskishan03/ProjectKyro"
homepage = "https://kyrodb.dev"
documentation = "https://docs.kyrodb.dev"
readme = "../README.md"
keywords = ["database", "kv", "learned-index", "rmi", "vector-search", "durability", "wal"]
categories = ["database-implementations", "data-structures", "concurrency"]
build = "build.rs"

[lib]
name = "kyrodb_engine"
path = "src/lib.rs"

[[bin]]
name = "kyrodb-engine"
path = "src/main.rs"

[features]
# Enable learned-index by default for consistent release binaries
default = ["learned-index", "grpc"]
learned-index = []
ann-hnsw = ["dep:hora"]
http-test = []
bench-no-metrics = []
# Optional CPU/SIMD build toggles
simd-avx2 = []
simd-avx512 = []
cpu-native = []
# Failure injection for tests
failpoints = ["dep:fail"]
grpc = ["dep:tonic", "dep:prost", "dep:prost-types"]

[dependencies]
tokio = { version = "1", features = ["full"] }
clap  = { version = "4", features = ["derive"] }
uuid  = { version = "1", features = ["serde", "v4"] }
chrono= { version = "0.4", features = ["serde"] }
warp = "0.3"
serde_json = "1.0"
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
sqlparser = "0.40"
hex = "0.4"
prometheus = "0.13"
once_cell = "1"
crc32c = "0.6"
memmap2 = "0.9"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
libc = "0.2"
dashmap = "5"
# ANN library (optional)
hora = { version = "0.1", optional = true }
# Small LRU cache for hot payloads (steady p99)
lru = "0.12"
# Structured logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "json"] }
# Failpoints for fault injection (optional)
fail = { version = "0.5", optional = true, features = ["failpoints"] }
# gRPC stack (feature-gated)
tonic = { version = "0.11", optional = true, default-features = true, features = ["transport"] }
prost = { version = "0.12", optional = true }
prost-types = { version = "0.12", optional = true }

[dev-dependencies]
tempfile = "3"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
loom = "0.7"
fail = { version = "0.5", features = ["failpoints"] }

[build-dependencies]
tonic-build = "0.11"
protoc-bin-vendored = "3"

[package.metadata.docs.rs]
features = ["learned-index", "ann-hnsw"]
