[package]
name = "kyrodb-engine"
version = "0.1.0"
edition = "2021"
authors = ["KyroDB Team <kishan@kyrodb.com>"]
license = "BUSL-1.1"
description = "High-performance database engine with learned indexes (RMI)"
repository = "https://github.com/vatskishan03/KyroDB"
homepage = "https://github.com/vatskishan03/KyroDB"
documentation = "https://github.com/vatskishan03/KyroDB"
readme = "../README.md"
keywords = ["database", "kv", "learned-index", "rmi", "performance", "durability", "wal"]
categories = ["database-implementations", "data-structures", "concurrency"]
build = "build.rs"

[lib]
name = "kyrodb_engine"
path = "src/lib.rs"

[[bin]]
name = "kyrodb-engine"
path = "src/main.rs"

[features]
# Core features only - focus on performance and simplicity
default = ["learned-index"]
learned-index = []
http-test = []
bench-no-metrics = []
# Optional CPU/SIMD build toggles for performance
simd-avx2 = ["dep:wide"]
simd-avx512 = ["dep:wide"]
cpu-native = []
# Failure injection for tests only
failpoints = ["dep:fail"]
# Optional rate limiting (disabled by default for max performance)
rate-limiting = []

[dependencies]
# Core async runtime
tokio = { version = "1", features = ["full"] }
# CLI parsing
clap  = { version = "4", features = ["derive"] }
# UUID generation for request IDs
uuid  = { version = "1", features = ["serde", "v4"] }
# Time handling
chrono= { version = "0.4", features = ["serde"] }
# HTTP server
warp = { version = "0.3", features = ["compression"] }
# JSON handling
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# Async streams
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
# Binary serialization
bincode = "1.3"
# Error handling
anyhow = "1.0"
# Cryptographic hashing
hex = "0.4"
# Metrics (feature-gated for zero-cost benchmarking)
prometheus = "0.13"
once_cell = "1"
# CRC for WAL integrity
crc32c = "0.6"
# Memory-mapped files for snapshots
memmap2 = "0.9"
# Fast hashing
xxhash-rust = { version = "0.8", features = ["xxh3"] }
# System calls
libc = "0.2"
# Concurrent hash maps
dashmap = "5"
# Zero-copy byte handling
bytes = "1.5"
# MessagePack for fast serialization
rmp-serde = "1.1"
# LRU cache for hot data
lru = "0.12"
# Atomic pointer swapping for lock-free reads
arc-swap = "1.6"
# Structured logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "json"] }
# High-performance locks
parking_lot = "0.12.4"
# Fast hashing for HashMap
ahash = "0.8"
# Stack-allocated vectors for performance
smallvec = { version = "1.11", features = ["serde"] }
# Fast non-cryptographic hashing
fnv = "1.0"
# Lock-free concurrent data structures
crossbeam-queue = "0.3"
# SIMD optimizations (optional)
wide = { version = "0.7", optional = true }
# Failpoints for testing (optional)
fail = { version = "0.5", optional = true, features = ["failpoints"] }
hyper = { version = "1.7.0", features = ["full"] }
hyper-util = { version = "0.1.17", features = ["full"] }
http-body-util = "0.1.3"

[dev-dependencies]
tempfile = "3"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
loom = "0.7"
fail = { version = "0.5", features = ["failpoints"] }
proptest = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "index_comparison"
harness = false

[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }

[package.metadata.docs.rs]
features = ["learned-index"]
