float:
  any:
    - name: kyrodb
      docker_tag: ann-benchmarks-kyrodb
      module: ann_benchmarks.algorithms.kyrodb
      constructor: KyroDB
      disabled: false
      base_args: ["@metric"]
      run_groups:
        M-16:
          args:
            M: 16
            ef_construction: 200
          query_args:
            &ef_search_sweep_default [
              [4, 8, 10, 20, 40, 80, 120, 200, 300, 400, 600],
            ]
        M-24:
          args:
            M: 24
            ef_construction: 200
          query_args: *ef_search_sweep_default
        M-36:
          args:
            M: 36
            ef_construction: 300
          query_args: *ef_search_sweep_default
        M-48:
          args:
            M: 48
            ef_construction: 300
          query_args:
            &ef_search_sweep_strong [
              [4, 8, 10, 20, 40, 80, 120, 200, 300, 400, 600, 800, 1200],
            ]
