[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
rand_distr = "0.4"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "gzip"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "2"
hdrhistogram = "7"
csv = "1"
indicatif = "0.17"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
kyrodb_engine = { path = "../engine", package = "engine" }
rand = "0.8"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"

[[bench]]
name = "kv_index"
harness = false
