[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
kyrodb_engine = { package = "engine", path = "../engine", features = ["learned-index"] }
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
criterion = { version = "0.5", features = ["async_tokio"] }
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
rand = "0.8"
serde_json = "1"
futures = "0.3"
base64 = "0.21"

[[bench]]
name = "kv_index"
harness = false
