name: Concurrency Tests

# Temporarily disabled to focus on write performance optimization
# Original triggers: workflow_dispatch, schedule (nightly), PR on engine paths
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  loom-setup:
    name: Setup Loom Environment
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (nightly for Loom)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Loom dependencies
        run: |
          echo "Loom tests run via regular cargo test with --features loom-tests"

      - name: Verify test setup
        run: |
          echo "Loom tests are available via: cargo test --features loom-tests -- --ignored"

  loom-core-tests:
    name: Loom Core Concurrency Tests
    runs-on: ubuntu-latest
    needs: loom-setup
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        test_type: ["snapshot_manifest", "rmi_concurrency"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Loom
        run: |
          echo "Using built-in Loom via Cargo features"

      - name: Run Loom ${{ matrix.test_type }} tests
        run: |
          cd engine
          cargo test --features loom-tests loom_${{ matrix.test_type }} --release -- --ignored

      - name: Run with different preemption levels
        run: |
          cd engine
          # Test with maximum preemption for thorough checking
          LOOM_MAX_PREEMPTIONS=3 cargo test --features loom-tests loom_${{ matrix.test_type }} --release -- --ignored
        continue-on-error: true

  loom-feature-tests:
    name: Loom Feature Variation Tests
    runs-on: ubuntu-latest
    needs: loom-setup
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        features: ["", "failpoints", "no-default"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Loom
        run: |
          echo "Using built-in Loom via Cargo features"

      - name: Run Loom tests with ${{ matrix.features }} features
        run: |
          cd engine
          if [ "${{ matrix.features }}" = "no-default" ]; then
            cargo test --no-default-features --features loom-tests --release -- --ignored
          elif [ "${{ matrix.features }}" = "failpoints" ]; then
            cargo test --features "failpoints,loom-tests" --release -- --ignored
          else
            cargo test --features loom-tests --release -- --ignored
          fi
        continue-on-error: true

  loom-extended:
    name: Loom Extended Testing
    runs-on: ubuntu-latest
    needs: [loom-core-tests, loom-feature-tests]
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Loom
        run: |
          echo "Using built-in Loom via Cargo features"

      - name: Run extended Loom tests
        run: |
          cd engine
          # Test with different thread counts and configurations
          echo "Testing with high branch limit..."
          LOOM_MAX_BRANCHES=2000 LOOM_MAX_PREEMPTIONS=2 cargo test --features loom-tests --release -- --ignored

          echo "Testing with maximum permutations..."
          LOOM_MAX_BRANCHES=1000 LOOM_MAX_PREEMPTIONS=1 cargo test --features loom-tests loom_rmi_concurrency --release -- --ignored

          echo "Testing with different model sizes..."
          LOOM_MAX_BRANCHES=500 LOOM_MAX_PREEMPTIONS=4 cargo test --features loom-tests loom_snapshot_manifest --release -- --ignored
        continue-on-error: true

  concurrency-summary:
    name: Concurrency Test Results
    runs-on: ubuntu-latest
    needs: [loom-core-tests, loom-feature-tests, loom-extended]
    if: always()

    steps:
      - name: Analyze test results
        run: |
          echo "=== Concurrency Test Summary ==="

          if [[ "${{ needs.loom-core-tests.result }}" == "success" ]]; then
            echo "✅ Core concurrency tests passed"
          else
            echo "❌ Core concurrency tests failed"
          fi

          if [[ "${{ needs.loom-feature-tests.result }}" == "success" ]]; then
            echo "✅ Feature variation tests passed"
          else
            echo "⚠️ Feature variation tests had issues (may be expected)"
          fi

          if [[ "${{ needs.loom-extended.result }}" == "success" ]]; then
            echo "✅ Extended concurrency tests passed"
          else
            echo "⚠️ Extended concurrency tests had issues (may be expected)"
          fi

          # Overall assessment
          if [[ "${{ needs.loom-core-tests.result }}" == "success" ]]; then
            echo ""
            echo "🎉 Concurrency testing completed successfully!"
            echo "Core race conditions have been validated."
          else
            echo ""
            echo "❌ Critical concurrency issues detected!"
            exit 1
          fi
