name: fuzz

on:
  workflow_dispatch:

jobs:
  fuzz-wal-snapshot:
    name: cargo-fuzz (manual)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Build fuzzers
        run: |
          cd engine
          # break workspace inheritance to avoid workspace build in CI
          echo "[workspace]" >> fuzz/Cargo.toml
          cargo fuzz build
          cargo fuzz list
          # ensure both targets build
          cargo fuzz build rmi_probe
      - name: Run RMI Probe Fuzzer
        run: |
          cd engine
          # Run fuzzing for a short duration to catch obvious bugs
          timeout 300 cargo fuzz run rmi_probe -- -max_len=1024 -runs=10000 || true
      - name: Run WAL Snapshot Fuzzer
        run: |
          cd engine
          # Run fuzzing for WAL/snapshot parsing
          timeout 300 cargo fuzz run fuzz_target_1 -- -max_len=1024 -runs=10000 || true
