name: fuzz

on:
  workflow_dispatch:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  fuzz-wal-snapshot:
    name: cargo-fuzz (manual/nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Build fuzzers
        run: |
          cd engine
          cargo fuzz build
          cargo fuzz list
      - name: Run RMI Probe Fuzzer
        run: |
          cd engine
          # Run fuzzing for a short duration to catch obvious bugs
          timeout 300 cargo fuzz run rmi_probe -- -max_len=1024 -runs=10000 || true
      - name: Run WAL Snapshot Fuzzer
        run: |
          cd engine
          # Run fuzzing for WAL/snapshot parsing
          timeout 300 cargo fuzz run fuzz_target_1 -- -max_len=1024 -runs=10000 || true
      - name: Upload crash artifacts (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-crash-artifacts
          path: |
            engine/fuzz/artifacts/
            engine/fuzz/crash-*
          retention-days: 30
