name: Cross-Platform Test Matrix

# Temporarily disabled to focus on write performance optimization
# Original triggers: workflow_dispatch, schedule (weekly Monday)
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  cross-platform-tests:
    name: Cross-Platform (${{ matrix.os }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            toolchain: stable
          - os: macos-latest
            arch: x86_64
            toolchain: stable
          - os: macos-latest
            arch: arm64
            toolchain: stable
          - os: windows-latest
            arch: x86_64
            toolchain: stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.arch != 'x86_64' && format('{0}-apple-darwin', matrix.arch) || '' }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.arch }}

      - name: Build kyrodb-engine (release)
        run: cargo build -p kyrodb-engine --release --locked

      - name: Build kyrodb-engine (debug)
        run: cargo build -p kyrodb-engine --locked

      - name: Test kyrodb-engine (default features)
        run: cargo test -p kyrodb-engine --all-targets --locked

      - name: Test kyrodb-engine (no default features)
        run: cargo test -p kyrodb-engine --no-default-features --all-targets --locked

      - name: Test kyrodb-engine (http-test feature)
        run: cargo test -p kyrodb-engine --features http-test --all-targets --locked

      - name: Test kyrodb-engine (failpoints feature)
        run: cargo test -p kyrodb-engine --features failpoints --all-targets --locked

  minimal-feature-test:
    name: Minimal Dependencies Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (stable, minimal)
        uses: dtolnay/rust-toolchain@stable

      - name: Build with minimal features
        run: |
          # Test with only essential dependencies
          cargo build -p kyrodb-engine --no-default-features --locked

      - name: Test with minimal features
        run: |
          cargo test -p kyrodb-engine --no-default-features --locked

  msrv-test:
    name: MSRV (Minimum Supported Rust Version)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (1.70.0 - MSRV)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.70.0

      - name: Build kyrodb-engine
        run: cargo build -p kyrodb-engine --locked

      - name: Test kyrodb-engine
        run: cargo test -p kyrodb-engine --locked
